### ISSUE TITLE
org.freedesktop.Secret.Service not available for use, secrets stored insecurely

### ISSUE THREAD

**Issue by The-Maize** [AchetaGames/Epic-Asset-Manager#227]
**Describe the bug**
After installing from flatpack, product works as advertised though shows error at the bottom of window. 
this is storing the "secret" information insecurely, kdewallet manager and wallet itself are both open and running when I launch this application.

**To Reproduce**
1. Open Application
2. look at bottom bar 
3. See error: "org.freedesktop.Secret.Service not available for use, secrets stored insecurely"

**Expected behavior**
Login and store information in a secure manner

**Desktop**
 - OS: Fedora 37 KDE - Kernel 6.0.18-300    AMD & Intel Based systems x86_64

**Comment by firebitsbr** [comment]
HowTo:

https://rtfm.co.ua/en/what-is-linux-keyring-gnome-keyring-secret-service-and-d-bus/

Install packages:
GUI:

[qdbusviewer](https://doc.qt.io/qt-5/qdbusviewer.html) – view objects and messages, is a part of the qt5-tools set
[d-feet](https://wiki.gnome.org/Apps/DFeet) – D-Bus debugger
[bustle](https://gitlab.freedesktop.org/bustle/bustle) – D-Bus message analyzer and profiler

And Run it:

$ d-feet

Open Epic-Asset-Manager, close and open again.

**Comment by aknarts** [comment]
Thank you @firebitsbr for providing the gudie, I should probably include it in some form of FAQ.

@The-Maize the issue is that KDE currently does not have an implementation of secret manager. AFAIK they are working on it. In the mean time the "insecure" means that they are unencrypted on the drive which is not any less secure than what Heroic launcher or even the official EGS store does, so there is no "real" concern in terms of exposing the secrets to the public. If your system is compromised to the point of these being at risk you probably have other problems.

**Comment by aknarts** [comment]
This is just a warning message. I need to see if keepass is able to serve as the secret service(if it listens through dbus correctly). Will install it in a VM to see if and how this can be made work.

**Comment by aknarts** [comment]
I do not think it is case sensitive. I do not doubt that it works, just not sure how gtk/flatpak talks to it there.

**Comment by aknarts** [comment]
I made a crucial decision to not display the warning anymore. I do have couple reasons for this:
 - It works on the supported DE (Gnome)
 - If it does not work it saves the secret like any other similar tool(looking at Legendary) which is presumably "secure enough"
 - I have no control over how every single DE implements their secret manager and if they all use the same standard
 - If and When there is a DE agnostic way of handling this I will use that instead of the current implementation but as of now this is "fine"

**Comment by aknarts** [comment]
How did you patch AUR?:) Just curious I can patch in in AUR as well if it works properly for most test cases
